language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: IqkQ48lgcovhADKbHAdAd7LE3j17HFhaRWoxGJ4yH2sSSKn3jQkicIsqCVTLID9lab1Dxdpjl7LVWyt3uXfiuiDWbHP8t4UM/IpsK2nDwtwESY3vHQUPh2+V0p54hhOx0/lIIsZihbKqjz0iR5DqllkAJLdkY3mk36MciM9PAHshq1n0t4Xepv/Q+Q3AaJmRjAydUwcYDXYm8yWirhmkjbWAg2VD9t566H4XE7WiTKpM7ulANQo+7vHtbqS8h4SWV1aa8kk6sqirX8FOJoiMyQvRGS/Qtrt3J8I0IJVh2LaW11lF5xYKTrk/v/cS2xfezOP6rwxrl+f82VKL9nAUu1ANC96j8KdPJOOR1r0cShbNdYxrMzCJ6gbbUoYpMCvF0iIg1m9mj6OeYxCx0KSOCpt/OMdZzeUpS59tcfHEa1Z7NzYA8AaatKD7REM4MH0ZbqJAPbAdK3P542+//ReYbYCnQQR8IkvyQY8ZeWDWiT09o0YAYNuPOCwBfJgZp4KB3DIfvU6NN4Kim1NJ7Kub5g5PMP5UlkfUBlqyiSd5AfWX80M24GcjUGWBZ1CKy1oQb94nz/zNYKKZANhZAazyphgI36C0cFoBLb2c68j2iyNjic1zYhCvwOTdVxiaKDDczwTgzbp03jHenQ8p42xmbdLdTxEPtCiwlIgdyV+y9oU=
  app: qmixi-crazybill
  on:
    repo: qmixi/crazybill